[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rayon = "1.10.0"
serde_json = "1.0"
kuchiki = "0.8.1"
indicatif = "0.17.7"
stop-words = "0.8"
ndarray = "0.15"
linfa = "0.6"
thiserror = "1.0"
flate2 = "1.0"


